# Lista 1 - Introdução ao Python

In [1]:
import numpy as np

#### 1. Crie os seguintes vetores :

**a) (1, 2, 3, . . ., 15)**

In [5]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**b) (15, 14, . . ., 1)**

In [8]:
np.arange(15,0,-1)

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

**c) (1, 2, 3, . . . , 19, 20, 19, 18, . . . , 2, 1)**

In [28]:
a = np.arange(40)
a[0:19] = np.arange(1,20)
a[20:41] = np.arange(20,0,-1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 19, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1])

In [79]:
np.concatenate((np.arange(1,20),np.arange(20,0,-1)), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1])

**d) (7, 8, 9) com o nome “a”**

In [34]:
a = np.arange(7,10,1)
a

array([7, 8, 9])

**e) (7, 8, 9, 7, 8, 9, . . ., 7, 8, 9) em que haja 9 ocorrências do 7**

In [89]:
np.tile(np.arange(7,10,1),8)

array([7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8,
       9])

**f) $(7, 8, 9, 7, 8, 9, . . ., 7, 8, 9, 7)$ em que haja 11 ocorrências do 7, 10 ocorrências do 8 e 10 ocorrências do 9**

In [101]:
np.concatenate((np.repeat(7,11),np.repeat(8,10),np.repeat(9,10)),axis=None)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9])

**g) $(7, 7, . . ., 7, 8, 8, . . ., 8, 9, 9, . . ., 9)$ em que haja 10 ocorrências do 7, 20 ocorrências do 8 e 30 ocorrências do 9**

In [99]:
np.concatenate((np.repeat(7,10),np.repeat(8,20),np.repeat(9,30)),axis=None)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

#### 2. Crie um vetor dos valores de $e^{x}\cos x$ em $x = 3; 3, 1; 3, 2; 3, 3; . . ., 6$

In [107]:
np.exp(np.arange(3.0,3.6,0.1)) * np.cos(np.arange(3.0,3.6,0.1))

array([-19.88453084, -22.17875339, -24.49069673, -26.77318244,
       -28.96923777, -31.01118644, -32.81977476])

#### 3. Crie os seguintes vetores: 

**a) $(0, 1)^3 (0, 2)^1 , (0, 1)^6 (0, 2)^4 , . . ., (0, 1)^{36} (0, 2)^{34}$**

In [109]:
((0.1) ** (np.arange(3,37,3)))* ((0.2) ** (np.arange(1,35,3)))

array([  2.00000000e-04,   1.60000000e-09,   1.28000000e-14,
         1.02400000e-19,   8.19200000e-25,   6.55360000e-30,
         5.24288000e-35,   4.19430400e-40,   3.35544320e-45,
         2.68435456e-50,   2.14748365e-55,   1.71798692e-60])

**b) $(2, \frac{2^2}{2},\frac{2^3}{3},...,\frac{2^{25}}{25})$**

In [111]:
(2 ** np.arange(1,26)) / np.arange(1,26)

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04,   9.98643810e+04,
         1.90650182e+05,   3.64722087e+05,   6.99050667e+05,
         1.34217728e+06])

### 4. Calcule

** a)** $\displaystyle\sum^{100}_{i=10}(i^3+4i^2)$

In [ ]:
# sum(seq(1,100)^3 + 4*(seq(1,100))^2)

**b)** $\displaystyle\sum^{25}_{i=10}(\frac{2^i}{i}+\frac{3^i}{i^2})$

In [112]:
# sum(((2^seq(1,25))/seq(1,25)) + (3^seq(1,25))/(seq(1,25))^2)